"""Editorial metadata scoring, not proof certification.
Derived from OpenAI math catalogue, Apache-2.0. Modified: extracted and annotated 2026-10-07.
No changes to the upstream checkout. Scores are explainable editorial heuristics, not measured virality.
"""
import json,pathlib,re
D=pathlib.Path(__file__).parent
C=json.loads((D/'catalog.json').read_text()); fs=C['families']; by={f['family_id']:f for f in fs}
# audience ease, visualization, surprise, plausible relevance. Evidence scored separately.
bases={
'Number theory':[2.5,2.7,3.1,2.0], 'Algebraic and complex geometry':[1.3,2.4,2.9,1.5],
'Real and complex analysis':[2.4,3.2,2.9,2.6], 'Convex and metric geometry':[2.8,3.6,2.9,2.5],
'Theoretical computer science':[3.0,3.3,3.2,3.5], 'Dynamical systems and ergodic theory':[2.7,3.5,3.0,2.8],
'Combinatorics':[3.4,3.8,3.2,2.4], 'Algebra':[1.6,2.2,3.0,1.6],
'Probability and statistical mechanics':[2.6,3.4,3.0,3.2], 'Mathematical logic':[2.4,2.6,3.6,2.6],
'Group theory':[1.9,2.6,3.1,1.9], 'Mathematical physics':[2.8,3.6,3.3,3.5],
'Operator algebras':[1.2,1.8,2.9,2.0], 'Topology':[1.8,2.8,3.0,1.8],
'Functional analysis':[1.9,2.5,2.8,2.5], 'Differential geometry':[2.1,3.4,3.0,2.3],
'Partial differential equations':[2.5,3.5,3.1,3.4]}
weights=dict(audience_ease=25,visualization=25,surprise=20,relevance=20,evidence_readiness=10)
manual={
'017':dict(scores=[5,5,5,2.5,3],zh='π 能被分数逼近到什么程度？',en='How closely can fractions imitate pi?',claim='对每个ν>2，所有充分大的分母q均满足|π−p/q|≥q^(−ν)；μ(π)=2。',novelty='从具体上界走向猜想中的精确值2；历史参照2019约7.1032和2026年9月预印本约7.10186，均不是新结论的独立认证。',visual='数轴缩放、22/7与355/113、误差随分母增长；用有限例外说明最终阈值。',impact='首先是丢番图逼近和Flint–Hills级数的理论结果；未找到直接工程收益。',caveats=['Q依赖ν且非有效','不能改写成所有q的1/q²下界','不推出有界连分数部分商或固定c/q²下界','不意味着更快计算π','selected comparator不含级数推论'],evidence='正文主定理与PiExponent独立目标静态对齐；存在解答模块。未独立编译；此论文不在yaml的162来源列表。',source_files=['preprints/The-irrationality-exponent-of-pi-is-2-September-24-2026/build/main.tex','preprints/The-irrationality-exponent-of-pi-is-2-September-24-2026/build/sections/interpolation.tex','preprints/The-irrationality-exponent-of-pi-is-2-September-24-2026/build/sections/conclusion.tex','lean/ComparatorChallenges/PiExponent.json'],external=['https://arxiv.org/abs/1912.06345','https://arxiv.org/abs/2609.11276']),
'158':dict(scores=[5,5,4.8,2.6,3],zh='给整个平面涂色，五种为什么不够？',en='Why might five colors fail to color the plane?',claim='任意五色平面染色都有相距恰好1的同色点；由既有七色上界得6≤χ(R²)≤7。',novelty='若成立，将de Grey 2018的下界5提高到6；不是确定最终答案。',visual='画单位距离连边、等边三角形、Moser spindle，再动画七色六边形铺砌。',impact='图论、几何组合的基础问题；与资源冲突图有概念联系，未证明无线网络性能改善。',caveats=['不是地图四色问题','允许任意不可测颜色类','尚未决定6或7','有限样例不能证明下界6','新下界的证明并非一张简单有限图'],evidence='范围说明和独立目标含任意染色及七色构造；静态材料存在，未独立编译。',source_files=['preprints/The-Euclidean-plane-is-not-five-colorable-September-23-2026/build/sections/introduction.tex','preprints/The-Euclidean-plane-is-not-five-colorable-September-23-2026/build/sections/rigidity.tex','lean/docs/158.md','lean/ComparatorChallenges/EuclideanFiveColor.json'],external=['https://arxiv.org/abs/1804.02385']),
'107':dict(scores=[4,4.2,5,4.4,3],zh='矩阵乘法的指数，能降到2.25？',en='Could the matrix-multiplication exponent fall to 2.25?',claim='复数域ω≤9/4；每个ε>0有Oε(n^(9/4+ε))算术运算的算法。',novelty='相较2026年8月原始论文上界2.371177，宣称显著降低渐近指数；不是2.25为最优值。',visual='二维矩阵点积到三阶张量，显示n³和n^(2.25+ε)增长曲线；图上标忽略常数的示意。',impact='矩阵运算是AI及数值计算基础；潜在算法基础价值极强，原文不提供实用规模竞争力。',caveats=['复数域','算术操作数不是位复杂度或GPU时间','ε及依赖ε的常数不可删除','不保证浮点稳定性','未展示AI训练实际提速'],evidence='主定理、真实有限算术程序定义与Comparator目标对齐；附源证明但未独立编译。',source_files=['preprints/Matrix-Multiplication-Nine-Fourths-October-2-2026/build/paper.tex','lean/docs/107.md','lean/ComparatorChallenges/MatrixMultiplication.lean','lean/OAI/LinearAlgebra/MatrixMultiplication/Main.lean'],external=['https://arxiv.org/abs/2608.16884','https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html']),
'003':dict(scores=[4.2,4.1,4.7,4,3],zh='黎曼猜想还没证明，但能排除一整条区域？',en='A zero-free strip is not the Riemann hypothesis',claim='所有Dirichlet L函数及Q(√−3)上的有限阶Hecke L函数在Re(s)>7/8无零点；允许s=1主特征极点。',novelty='固定且对导子/高度一致的零点排除带，及相关Siegel零点排除。',visual='复平面上1/2、7/8、1三条线，清晰保留未排除区域。',impact='素数分布与解析数论的重要基础控制；没有证明RSA失效或实际密码攻击。',caveats=['严格>7/8，不含边界','不等于RH或GRH','s=1极点要排除','不是任意数域全部L函数'],evidence='有四个对应Comparator及scope；不等于其后所有应用已形式化；未独立编译。',source_files=['preprints/The-Quasi-Riemann-Hypothesis-September-30-2026/build/paper.tex','lean/docs/003.md'],external=['https://www.claymath.org/millennium/riemann-hypothesis/']),
'376':dict(scores=[4.3,4.5,4.8,3,2.8],zh='一滴被精心驱动的流体，能模拟计算机吗？',en='Can a carefully forced fluid simulate a computer?',claim='为机器和输入构造光滑外力下的不可压黏性流，使固定检测事件等价于停机；各伴随稿的空间、外力及检测器不同。',novelty='有效有限程序、从静止出发及具体检测器/外力限制的加强。',visual='染色流体粒子穿过逻辑路径，到达检测区对应停机。',impact='动力系统可计算性与预测边界；不是可制造、抗噪或高效的流体电脑。',caveats=['人为设计且通常随机器/输入变化的外力','不是一般Navier–Stokes正则性','不是无外力结果','不保证有限精度或噪声鲁棒性','不能混搭不同伴随稿的最强条件'],evidence='多个scope段与Comparator各有独立范围；尚未执行核验。',source_files=['lean/docs/376.md','preprints/Universal-Computation-with-Eventually-Stationary-Navier-Stokes-Forcing-September-27-2026/manuscript.pdf'],external=[]),
'362':dict(scores=[3.8,4.5,4.5,3.6,3],zh='等离子体方程会不会在有限时间失控？',en='Can relativistic plasma equations develop a finite-time singularity?',claim='三维单物种相对论Vlasov–Maxwell，对满足条件的任意大小光滑初值给全局经典唯一解。',novelty='从特定小数据/对称或条件结论走向所列大数据的一般情形。',visual='粒子相空间云、电磁场与时间演化；区分物理示意和数学证明。',impact='无碰撞等离子体模型的数学基础；不是等离子体稳定性、融合控制或数值精度保证。',caveats=['粒子密度非负且光滑紧支撑','场有限能量、所有阶导数有界','满足两条Gauss约束','单物种','每个有限时间区间光滑≠所有时间统一有界'],evidence='主结果条件在scope与Comparator明确出现；未独立编译。',source_files=['lean/docs/362.md','preprints/Global-classical-solutions-of-the-three-dimensional-relativistic-Vlasov-Maxwell-system-September-23-2026/paper.pdf'],external=[]),
'179':dict(scores=[4.2,4.5,4,3.3,3],zh='完美回声码为什么不能任意长？',en='Why can’t ideal binary echo codes be arbitrarily long?',claim='实循环Hadamard矩阵只在阶1、4存在；结合旧奇数结论，长度>1的Barker码恰为2,3,4,5,7,11,13。',novelty='补齐Barker猜想的偶数长度一侧；奇数结果来自既有工作。',visual='±1脉冲与延迟副本相乘求和，显示主峰和旁瓣。',impact='Barker码在脉冲压缩/同步中已有应用；新非存在性证明限制特定理想码族，不提升现有雷达性能。',caveats=['仅二值±1、非周期自相关绝对值≤1','不限制所有多相码或其他目标函数','Lean选定扩展只覆盖偶数长度','现有应用是旧码的应用'],evidence='循环矩阵及偶Barker长度两个Comparator；完整奇数分类为论文调用旧结果。未独立编译。',source_files=['preprints/The-circulant-Hadamard-conjecture-September-23-2026/build/sections/introduction.tex','lean/docs/179.md'],external=['https://arxiv.org/abs/1501.06035','https://www.mathworks.com/help/phased/ug/waveform-analysis-using-the-ambiguity-function.html']),
'130':dict(scores=[4,4.4,4.4,3.2,2.4],zh='比FFT更少的运算？先看计算模型',en='Fewer operations than the FFT? Read the model first',claim='较强稿声称每个n的精确复数DFT可用O(n(log n)^(1−10^−13))操作；形式化伴随稿只给无界长度子序列上任意小归一化电路成本。',novelty='在无限精确、无界系数模型中突破相关n log n尺度，不能迁移给有界系数下界。',visual='波形拆频率、蝶形电路，以及“所有长度”和“某些越来越大长度”的双时间线。',impact='傅里叶计算本身有广泛应用；此模型和极小节省尚未给实用FFT或信号处理速度收益。',caveats=['强稿与形式化稿不同','精确复算术且系数不受限','无位复杂度/稳定性保证','强稿需给定指定单位根','巨大常数及无可用交叉点'],evidence='ExactFourier Comparator明确只有subsequence量词；不能给全长度稿贴Lean验证标签。未独立编译。',source_files=['lean/docs/130.md','lean/ComparatorChallenges/ExactFourier.lean','preprints/An-explicit-power-saving-for-the-exact-discrete-Fourier-transform-September-25-2026/build/sections/introduction.tex'],external=[]),
'102':dict(scores=[3.7,4.2,4.5,3.5,3],zh='“差不多最优”也有数学上的极限？',en='Can even “almost optimal” be computationally hard?',claim='Unique Games存在固定误差参数的多项式间隙归约；Max-Cut、Vertex Cover等阈值还有直接伴随论证。',novelty='若成立，给长久条件性的近似困难结论去掉UGC前提；依然不证明P≠NP。',visual='图上割边、可满足99%与至多1%的差距；区分找答案与检查答案。',impact='优化算法能保证什么的理论边界，帮助选择近似目标；不是所有实例都不可处理。',caveats=['有效不能超越界须P≠NP','固定参数先于输入规模','最坏情况','不排除启发式在真实数据上的好结果'],evidence='具体二进制输入、有限机归约、简单二分图与误差量词在Comparator中；未独立编译。',source_files=['lean/docs/102.md','preprints/The-Unique-Games-Theorem-September-23-2026/build/sections/00-introduction.tex','preprints/The-Unique-Games-Theorem-September-23-2026/build/sections/07-consequences.tex'],external=[]),
'265':dict(scores=[3.6,4.5,4.3,4.3,1],zh='量子纠缠的复杂度能按边界计算吗？',en='Can a quantum state’s entanglement be controlled by its boundary?',claim='二维局域哈密顿量的唯一基态，在全系统谱隙等条件下满足面积律；另稿给开方格上多项式bond维PEPS逼近。',novelty='宣称二维一般全局谱隙条件下的面积律及PEPS存在性推进。',visual='方格量子自旋网、切开区域、边界长度与内部面积对比。',impact='潜在奠定张量网络压缩/模拟的理论基础；未给有效构建或收缩算法。',caveats=['唯一基态、局域相互作用有界、均匀谱隙','不同稿条件不可混合','存在逼近≠多项式时间找出/收缩','未找到本族Lean形式化'],evidence='手稿定理与限制已阅读；无该族scope/catalogue形式化项，证据成熟度低。',source_files=['preprints/A-two-dimensional-area-law-from-a-global-spectral-gap-September-24-2026/paper.pdf','preprints/Polynomial-PEPS-approximation-of-gapped-square-grid-ground-states-September-24-2026/paper.pdf'],external=[])
}
importance=[('003',99,'固定零点排除区域及解析数论广泛依赖；不是完整RH。'),('032',98,'CM阿贝尔簇Hodge及经已知桥梁的Tate/标准猜想影响；不等于所有簇Hodge。'),('004',97,'有理数丢番图可判定性的基础界限。'),('102',96,'理论计算机科学近似阈值的大范围条件依赖。'),('002',95,'低Selmer余秩全BSD及有限性；须保留低余秩范围。'),('287',94,'自由群因子同构这一算子代数结构中心问题。'),('362',93,'相对论动理学大数据全局正则性的基础问题。'),('159',92,'Erdős倒数和猜想与定量Szemerédi的核心组合数论意义。'),('265',91,'二维量子多体面积律与压缩表述的理论基础。'),('107',90,'基础算法的复杂度指数及使用矩阵运算的算法。')]
imp={i:(n+1,s,r) for n,(i,s,r) in enumerate(importance)}
entries=[]
for f in fs:
 fid=f['family_id']; scores=list(bases[f['discipline']]); reasons=[f"Category baseline: {f['discipline']}"]
 text=f['title'].lower()
 adjustments=[]
 for pattern,ix,delta,label in [(r'counterexample|nonuniqueness|fails|failure|undecid',2,0.5,'counterintuitive negative-result title'),(r'color|tiling|packing|covering|sphere|billiard|distance|triangle|circle',1,0.35,'geometric/combinatorial visual objects'),(r'polynomial.time|almost.linear|multiplication|fourier|sampling|matching|scheduling',3,0.35,'algorithmic title suggests possible methods relevance'),(r'π|catalan|goldbach|prime|riemann',0,0.35,'recognizable elementary object/name')]:
  if re.search(pattern,text):scores[ix]=min(5,scores[ix]+delta);adjustments.append(label)
 scores.append(2.4 if f['formalization']['comparators'] else (1.8 if f['formalization']['scope_doc_path'] else 1.0))
 ev='No independent compilation. Scope docs and source/configuration presence are metadata evidence, not proof certification.'
 entry={'family_id':fid,'title':f['title'],'discipline':f['discipline'],'assessment_level':'metadata_heuristic_not_full_proof_review','score_explanation':reasons+adjustments,'scores_0_to_5':dict(zip(weights,scores)),'evidence_note':ev,'novelty_status':'Claimed novelty from repository; no family-by-family priority or correctness certification','proof_audit_status':'not_independently_compiled','manuscript_count':f['manuscript_count'],'primary_pdf_url':f['manuscripts'][0]['pdf_url'],'scope_doc_path':f['formalization']['scope_doc_path']}
 if fid in manual:
  m=manual[fid];entry.update({k:v for k,v in m.items() if k!='scores'});entry['scores_0_to_5']=dict(zip(weights,m['scores']));entry['assessment_level']='manual_editorial_calibration_with_selected_theorem_and_scope_reading';entry['score_explanation']=['Manual calibration for broad Chinese/English visual explainers; consult claim, impact, caveats and evidence fields.']
 entry['virality_heuristic_score_100']=round(sum(entry['scores_0_to_5'][k]*w/5 for k,w in weights.items()),2)
 # Not in the manually chosen top ten: retain uncertainty. No fabricated precise importance order.
 if fid in imp:entry['foundational_importance_top10']={'rank':imp[fid][0],'editorial_score':imp[fid][1],'reason':imp[fid][2],'conditional_on_correctness':True}
 entries.append(entry)
entries.sort(key=lambda e:(-e['virality_heuristic_score_100'],e['family_id']))
for i,e in enumerate(entries):e['communication_rank']=i+1
actual=[e['family_id'] for e in entries[:10]]
expected=['017','158','107','003','376','362','179','102','130','265']
assert actual==expected,(actual,[(e['family_id'],e['virality_heuristic_score_100']) for e in entries[:15]])
obj={'schema_version':'1.0','snapshot_commit':C['commit'],'review_date_utc':'2026-10-07','purpose':'Editorial queue for 372 bilingual explainers; production progress is recorded separately in production_status.json. Rankings do not certify proofs or imply completed videos.','method':{'weights_percent':weights,'formula':'sum(score_0_to_5 * weight_percent / 5)','definitions':{'audience_ease':'5=can motivate with school-level objects; 1=requires extensive graduate prerequisites','visualization':'5=faithful intuitive animation possible; diagrams are not proof','surprise':'5=strong recognizable prior-bound/barrier or counterintuitive hook','relevance':'5=large plausible mathematical/computational/physical consequence; not a claim of deployment','evidence_readiness':'1=manuscript claim only; 2.4=scope and comparator metadata; around3=selected statement/source aligned by static reading; 5 reserved for stronger independently reproduced checks and appropriate review; not probability of truth'},'category_baselines':bases,'title_adjustments':'See per-entry score_explanation; title keywords can add 0.35 to visual/ease/relevance and 0.5 to surprise. Manual top ten replace these values.','limits':['Not predicted view counts','Not a rigorous total order of mathematical importance','Full catalogue metadata coverage does not mean full reading of all 722 proofs','All proof correctness and external acceptance remain qualified','Before producing each later video, reread its actual paper, audit scope, recheck current version and sources']},'top10_communication_ids':actual,'top10_foundational_importance':[{'rank':i+1,'family_id':fid,'score':sc,'reason':why,'conditional_on_correctness':True} for i,(fid,sc,why) in enumerate(importance)],'potential_real_world_relevance_order':['107','265','362','102','130','179','269','271','120','109'],'real_world_relevance_warning':'This separate editorial ordering concerns potential relevance, not realized industrial impact, validated speedup, or proof reliability.','entries':entries}
(D/'ranking.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print([(e['communication_rank'],e['family_id'],e['virality_heuristic_score_100']) for e in entries[:10]])
